const express = require("express");
const router = express.Router();
const userController = require("../controller/userController");
router.get("/", userController.landingPage);
router.get("/posts", userController.posts);
router.post("/register", userController.register);
router.post("/signin", userController.signin);
router.put("/:id", userController.userUpdate);
router.delete("/:id", userController.removeAccount);
router.get("/:id", userController.userGet);
router.get("/follow/:id", userController.followUser);
router.get("/unfollow/:id", userController.unFollow);
module.exports = router;
